# Generated by Django 3.1.7 on 2021-06-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituer',
            name='date_ajout',
        ),
    ]
