# Generated by Django 3.1.7 on 2021-06-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Projet', 'Projet'), ('Magasin', 'Magasin'), ('IT', 'IT'), ('RH', 'RH')], default='Choose me', max_length=200)),
                ('objet', models.CharField(max_length=200)),
                ('description_reclamation', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('statut', models.CharField(choices=[('en attente', 'en attente'), ('prise en charge', 'prise en charge'), ('en traitement', 'en traitement'), ('terminé', 'terminé')], max_length=200)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_solution', models.IntegerField()),
                ('description_solution', models.TextField()),
                ('date_solution', models.DateField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionReclamation.reclamation')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.utilisateur')),
            ],
        ),
    ]
