# Generated by Django 3.1.7 on 2021-06-20 13:56

import GestionProjet.custom_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Magasin', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef_Projet',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.utilisateur')),
            ],
            bases=('general.utilisateur',),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('description_projet', models.TextField(blank=True)),
                ('adresse_projet', models.CharField(max_length=200)),
                ('date_ajout_projet', models.DateTimeField(auto_now_add=True)),
                ('cout_projet', models.FloatField(null=True, validators=[GestionProjet.custom_validators.validate_interval])),
                ('delai_projet', models.PositiveIntegerField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('etat_projet', models.CharField(choices=[('a faire', 'a faire'), ('en cours', 'en cours'), ('terminé', 'terminé')], max_length=200, null=True)),
                ('caracteristique_projet', models.TextField(blank=True)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.chef_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable_Projet',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='general.utilisateur')),
            ],
            bases=('general.utilisateur',),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_tache', models.CharField(max_length=200)),
                ('description_tache', models.TextField()),
                ('mots_clés', models.CharField(max_length=1000)),
                ('demarche_tache', models.TextField(blank=True, null=True)),
                ('difficulté_tache', models.TextField(blank=True, null=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.projet')),
            ],
        ),
        migrations.CreateModel(
            name='DetailleAffectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Magasin.article')),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionProjet.chef_projet')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProjet.projet')),
            ],
            options={
                'unique_together': {('projet', 'article')},
            },
        ),
    ]
