# Generated by Django 3.1.7 on 2021-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionProjet', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailleaffectation',
            unique_together=set(),
        ),
    ]
