# Generated by Django 3.1.7 on 2021-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('date_naiss', models.DateField()),
                ('adresse', models.CharField(max_length=800, null=True)),
                ('email', models.CharField(max_length=800, null=True)),
                ('telephone', models.CharField(max_length=8, null=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('Responsable', 'Responsable'), ('chefProjet', 'chefProjet'), ('ResponsableMagasin', 'ResponsableMagasin')], max_length=200, null=True)),
                ('motDePasse', models.CharField(max_length=50)),
            ],
        ),
    ]
